### ISSUE TITLE
AzureTestcasesService.cs - Missing the file extension ".dll" from the AutomatedTestStorage field.

### ISSUE THREAD

**Issue by 48x16** [AutomateThePlanet/BELLATRIX#13]
Hi Again,

Just working through the Azure dynamic test case plugin. I noticed it's updating the Associated Automation / Automated test storage field without appending the .dll on the end. When a tester comes to execute the test through the test plan, the release pipeline cannot find the tests and fails.

I have simply appended the .dll to the end for now. I don't know if you'd expect to have different containers aside from .dlls? 

![image](https://user-images.githubusercontent.com/37348105/160149163-52352680-02f4-4b77-84f9-291101ae030e.png)

I don't even know if you'd count it as an 'issue', maybe just helpful if someone else discovers this behaviour. 

Thanks again for the framework, it's working really well for my use case.

**Comment by angelovstanton** [comment]
To be honest I have tested only whether the association is added to the test cases but I haven't try to execute the test cases via Test Plan since in most of our projects we use other systems. If you believe that this is the correct behavior and you have tested it, feel free to submit a PR and I will merge it. :)

**Comment by angelovstanton** [comment]
Thank you for the PR I have just merged it
