### ISSUE TITLE
Parallel Selenium web testing with MsTest 

### ISSUE THREAD

**Issue by ectoplasmid** [AutomateThePlanet/BELLATRIX#19]
It looks like the current version doesn't allow for more than one web test at a time. 
Even with parallel testing enabled in the settings all other open browsers would be closed immediately.
When working around that test sessions seem not to be distributed to the correct test. I saw that the driver create service is static and wonder if that is part of the problem.

**Comment by angelovstanton** [comment]
The parallel support works only by class. It is not related to the static instances since in C# version we achieve the thread-safe via Unity sub containers. There is an option in the config - isParallelExecutionEnabled which you need to set to true if you plan to run in parallel it will disable the automatic cleaning of drivers and browsers.
